---
- name: provision
  hosts: registry
  tasks:
  - name: Ensure dependencies are present
    apt:
      pkg:
      - docker
      - docker-compose
      state: present
    become: yes
  - name: Enable and run the registry services
    community.docker.docker_compose:
      project_name: registries
      definition:
        version: '3'
        services:
          docker:
            image: registry:2
            ports:
            - "5000:5000"
            environment:
            - "REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io"
          k8s_gcr:
            image: registry:2
            ports:
            - "5001:5000"
            environment:
            - "REGISTRY_PROXY_REMOTEURL=https://k8s.gcr.io"
          quay:
            image: registry:2.5
            ports:
            - "5002:5000"
            environment:
            - "REGISTRY_PROXY_REMOTEURL=https://quay.io"
          gcr:
            image: registry:2
            ports:
            - "5003:5000"
            environment:
            - "REGISTRY_PROXY_REMOTEURL=https://gcr.io"
          ghcr:
            image: registry:2
            ports:
            - "5004:5000"
            environment:
            - "REGISTRY_PROXY_REMOTEURL=https://ghcr.io"
