name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  validate-terraform:
    name: 'Build'
    runs-on: 'ubuntu-latest'
    steps:
    - name: Clone the Repo
      uses: actions/checkout@v2

    - name: Run Terraform init
      uses: docker://hashicorp/terraform:1.1.8
      with:
        entrypoint: terraform
        args: -chdir=terraform init

    - name: Run Terraform validate
      uses: docker://hashicorp/terraform:1.1.8
      with:
        entrypoint: terraform
        args: -chdir=terraform validate
