name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  validate-terraform:
    name: 'terraform validate'
    runs-on: 'ubuntu-latest'
    steps:
    - name: Clone the Repo
      uses: actions/checkout@v2

    - name: Run Terraform init
      uses: docker://hashicorp/terraform:1.1.8
      with:
        entrypoint: terraform
        args: -chdir=terraform init

    - name: Run Terraform validate
      uses: docker://hashicorp/terraform:1.1.8
      with:
        entrypoint: terraform
        args: -chdir=terraform validate

    - name: Run Terraform init - testing
      uses: docker://hashicorp/terraform:1.1.8
      with:
        entrypoint: terraform
        args: -chdir=terraform/testing init

    - name: Run Terraform validate - testing
      uses: docker://hashicorp/terraform:1.1.8
      with:
        entrypoint: terraform
        args: -chdir=terraform/testing validate


  validate-talos-playbook:
    name: 'talos validate'
    runs-on: 'ubuntu-latest'
    env:
      REGISTRY: ghcr.io
      GHCR_USERNAME: j-lgs
    steps:
    - name: Clone the Repo
      uses: actions/checkout@v2

    - name: Playbook run
      uses: 'docker://ghcr.io/j-lgs/playbook-verify:latest'
      with:
        args: talos/generate-talos-patches.yaml

